PROJECT_NAME := blupoi
NRF5_SDK     ?= $(ROOT)/sdk/12
NRF_TARGET   ?= nrf52
NRF_SOC      ?= NRF52832

GNU_INSTALL_ROOT := /usr
GNU_PREFIX := arm-none-eabi


# Modify this file or override using enviroment variables

